apiVersion: v1
kind: ReplicationController
metadata:
  name: jetty-rc
  labels:
    name: jetty
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: jetty
    spec:
      containers:
      - name: jetty-rc-pod
        image: happywhaler/simplewebapp:latest
        ports:
        - containerPort: 8080