apiVersion: v1
kind: Service
metadata:
  name: jetty-service
  labels:
    name: jetty-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: jetty